-- 코드를 입력하세요
SELECT F.CATEGORY, SUB.MAX_PRICE, F.PRODUCT_NAME FROM
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) SUB JOIN FOOD_PRODUCT F ON SUB.CATEGORY = F.CATEGORY
WHERE SUB.MAX_PRICE = F.PRICE AND F.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY SUB.MAX_PRICE DESC
