-- 코드를 입력하세요

SELECT Y, M, G, COUNT(*) FROM (
SELECT YEAR(SALES_DATE) AS Y, MONTH(SALES_DATE) AS M, S.USER_ID, U.GENDER AS G
FROM ONLINE_SALE S JOIN USER_INFO U ON S.USER_ID = U.USER_ID 
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), S.USER_ID, U.GENDER) B
GROUP BY Y, M, G
ORDER BY Y, M, G

