-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100)
AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON D.CAR_TYPE = C.CAR_TYPE AND D.DURATION_TYPE LIKE '30%'
WHERE C.CAR_TYPE IN ('SUV', '세단')
AND C.CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
AND C.DAILY_FEE * 30 - C.DAILY_FEE * 30 * D.DISCOUNT_RATE / 100 >= 500000 AND C.DAILY_FEE * 30 - C.DAILY_FEE * 30 * D.DISCOUNT_RATE / 100 < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC