-- 코드를 입력하세요
SELECT A.HOUR, IFNULL(B.CNT, 0) AS COUNT
FROM
(SELECT ROW_NUMBER() OVER (ORDER BY NAME) - 1 AS HOUR FROM ANIMAL_OUTS LIMIT 24) A
LEFT OUTER JOIN
(
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) B
ON A.HOUR = B.HOUR
ORDER BY A.HOUR