-- 코드를 작성해주세요
SELECT E2.YEAR AS YEAR, E2.SIZE - E1.SIZE_OF_COLONY AS YEAR_DEV, E1.ID
FROM ECOLI_DATA E1 JOIN
(SELECT ROW_NUMBER() OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE) ORDER BY SIZE_OF_COLONY DESC) AS RN, YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY AS SIZE
FROM ECOLI_DATA) E2
ON YEAR(E1.DIFFERENTIATION_DATE) = E2.YEAR
WHERE E2.RN = 1
ORDER BY YEAR, YEAR_DEV