-- 코드를 작성해주세요

SELECT A.FISH_COUNT, B.MAX_LENGTH, A.FISH_TYPE
FROM (
    SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH, 10)) >= 33
) A JOIN (
    SELECT FISH_TYPE, MAX(IFNULL(LENGTH,10)) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) B ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.FISH_TYPE
