-- 코드를 작성해주세요
# SELECT ID, CASE WHEN RANK
SELECT ID, CASE WHEN L_RANK / TOTAL * 100 <= 25 THEN 'CRITICAL'
                WHEN L_RANK / TOTAL * 100 <= 50 THEN 'HIGH'
                WHEN L_RANK / TOTAL * 100 <= 75 THEN 'MEDIUM'
                ELSE 'LOW'
           END AS COLONY_NAME
FROM
(SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS L_RANK, COUNT(*) OVER() AS TOTAL
FROM ECOLI_DATA) A
ORDER BY ID